spring:
  application:
    name: test-eureka-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://xxx.com:8761/eureka/,http://xxx.com:8761/eureka/,http://xxx.com:8761/eureka/,http://xxx.com:8761/eureka/

test:
  eureka:
    namespace: test-eureka-provider