---
spring:
  profiles: node1
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: xxx.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://xxx.com:8761/eureka/,http://xxx.com:8761/eureka/

---
spring:
  profiles: node2
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: xxx.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://xxx.com:8761/eureka/,http://xxx.com:8761/eureka/

---
spring:
  profiles: node3
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: xxx.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://xxx.com:8761/eureka/,http://xxx.com:8761/eureka/